config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parks do
    resources :visits, only: [:index]
  end
  root 'parks#index'
  resources :users do
   resources :visits, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :image, presence: true
  # validates :address, presence: true, if: -> { latitude.nil? || longitude.nil? }
  # validates :longitude, presence: true, if: -> { address.nil? }
  # validates :latitude, presence: true, if: -> { address.nil? }
  mount_uploader :image, ImageUploader
  attr_accessor :raw_address
  geocoded_by :raw_address
  reverse_geocoded_by :latitude, :longitude
   after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }
  after_validation :reverse_geocode, unless: ->(obj) { obj.address.present? },
                   if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and
                    obj.longitude.present? and obj.longitude_changed? }
  has_many :visits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  has_many :visits
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :park
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :latitude, :longitude, :address, :image])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :latitude, :longitude, :address, :image])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.order('name DESC')
  end

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    if @park.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def show
    @park = Park.find(params[:id])
  end

  private

  def park_params
    params.require(:park).permit(:name, :raw_address, :description, :image, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # before_action :set_visit, only: [ :show, :destroy ]

  def index
    @visits = Visit.where(user: current_user)
  end

  def new
    @visit = Visit.new
  end

  def create
    @visit = Visit.new(visit_params)
    @user = current_user
    @park = Park.find(params[:park_id])
    @visit.user_id = @user.id
    @visit.park_id = @park.id
    if @visit.save
      flash[:success] = "Your Visit has been saved!"
      redirect_to user_visits_path(user_id: current_user)
    else
      render 'new'
    end
  end

  def show
    @visit = Visit.find(params[:id])
  end

  def destroy
    @visit = Visit.find(params[:id])
  end

  private

  def visit_params
    params.require(:visit).permit(:user_id, :park_id, :date)
  end

  # def set_visit
  #   @visit = Visit.find(params[:id])
  # end

  # def set_parks
  #   @parks = Parks.all.by_name
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_banner.html.erb
<div id="blurred-image-container">
  <div class="img-src"></div>
  <div class="img-src blurred-image"></div>
</div>
<div class="banner">
  <div class="blur">
    <h1>Never Miss a Game.<br>Every Season.</h1>
  </div>
</div>
<div class="banner-small">
ParkChasr allows you to track all your attended games and explore new ones.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Park Chasr</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/parks/_form.html.erb
<header><h1 class="display-4 add-park" align="center">Add a New Park</h1></header>

<div class='row'>
  <div class="add-park-container container">
  <div class ='col-xs-12'>
    <%= form_for(@park, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class='control-label col-sm-4'>
        </div>
        <div class='col-sm-4'>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name of the BallPark', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class='control-label col-sm-4'>
        </div>
         <div class='col-sm-4'>
          <%= f.text_field :description, class: "form-control", placeholder: "Home Stadium of the ....." %>
         </div>
       </div>
      <div class="form-group">
        <div class='control-label col-sm-4'>
        </div>
         <div class='col-sm-4'>
          <%= f.text_field :raw_address, class: "form-control", placeholder: "Add Stadium Address or...." %>
         </div>
       </div>
       <div class="form-group">
        <div class='control-label col-sm-4'>
        </div>
         <div class='col-sm-4'>
          <%= f.text_field :latitude, class: "form-control", placeholder: "...use latitude" %>
         </div>
       </div>
       <div class="form-group">
        <div class='control-label col-sm-4'>
        </div>
         <div class='col-sm-4'>
          <%= f.text_field :longitude, class: "form-control", placeholder: "and longitude" %>
         </div>
       </div>
       <div class="form-group add-photo">
        <div class='control-label col-sm-4 add-photo'>
        </div>
         <div class='col-sm-4'>
         <%= f.file_field :image%>
         </div>
        </div>
        <div class="form-group">
          <div class='control-label col-sm-4'>
        </div>
         <div class="control-label col-sm-4">
          <%= f.submit "Add Park", class: "btn btn-primary" %>
         </div>
        </div>
    <% end %>
  </div>
  </div>
</div>

app/views/parks/index.html.erb
 <%= render 'layouts/banner' %>

<div class="container-index">
      <div class="row">
          <% @parks.each do |park| %>
              <%= link_to park_path(park) do %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card" style="background-image: url(<%= park.image %>)">
                  <div class="card-category"><%=park.name%>
                  </div>
                  <div class="card-description">
                    <h2><%= park.description %></h2>
                    <p><%= park.address %></p>
                  </div>
              </div>
            <% end %>
          </div>
      <% end %>
    </div>
  <div class="row" align="center" >
    <h3>Don't see the stadium you're looking for? Add one.</h3>
    <%= link_to 'Add Stadium', new_park_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <body>

  </body>
</div>

app/views/parks/new.html.erb
<div class="add-park-wrapper wrapper">
<%= render 'form' %>
</div>

app/views/parks/show.html.erb
<img style="background-image: url(<%= cl_image_path @park.image %>)" class="park-banner">
</div>



<div>
  <div class="show-container">
    <div class="show-cards-container">
      <div class="park-profile show-card">
        <div class="park-name">
          <h1><%= @park.name %></h1>
        </div>

        <div class='flex'>
              <div class='flex-column'>
               <i class="fas fa-baseball-ball"></i>
                <p><%= @park.description.capitalize %></p>
              </div>
              <div class="flex-column">
                <i class="fas fa-map-marker-alt"></i>
                <p><%= @park.address %></p>
              </div>
              <div class='flex-column'>
                <i class="fas fa-map-marker-alt"></i> <p>Latitude: <%= @park.latitude %> </p>
              </div>
              <div class='flex-column'>
                <i class="fas fa-map-marker-alt"></i> <p>longitude: <%= @park.longitude %></p>
              </div>
        </div>
      </div>

      <div class="show-card park-description">
        <p>
          <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@park.latitude},#{@park.longitude}&markers=#{@park.latitude},#{@park.longitude}&zoom=7&size=640x400&key=#{ENV['GOOGLE_API']}",
              class: 'img-fluid img-rounded', alt: "#{@park.name} on the map" %>
        </p>
      </div>
      <div class="show-card park-visits">
          <h2>Your Distance from Stadium: <%= current_user.distance_to(@park).to_i %> milies  </h2>
          <p><%=@park.visits.count %> other users have been to this stadium</p>
      </div>
    </div>
    <div class="show-card book-form">
        <%= simple_form_for(:visit, url: park_visits_path(park_id: @park.id), method: :post) do |f| %>
          <%= f.input :date, as: :string, required: true, placeholder: "YYYY-MM-DD"  %>
          <%= f.submit "Create Your Visit", class: "form-btn", id: "sweet-alert"%>
        <% end %>
      </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <i class="fas fa-baseball-ball"></i>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <%= link_to "My Visits", user_visits_path(user_id: current_user), class: "nav-link" %>
    </div>
      <div class="navbar-wagon-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </div>
    <% else %>
      <div class="navbar-wagon-item">
        <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
      </div>
      <div class="navbar-wagon-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>
    <% end %>




    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
       <!--  <img src=<%= current_user.image if user_signed_in?%> class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <div class="navbar-wagon-item">
            <%= link_to "Parks", parks_path, class: "drop-link" %>
          </div>
        </li>
        <% if user_signed_in? %>
        <li>
          <div class="navbar-wagon-item">
            <%= link_to "Profile", user_path(current_user), class: "drop-link" %>
          </div>
        </li>
        <li>
          <div class="navbar-wagon-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "drop-link" %>
          </div>
        </li>
        <% else %>
          <li>
            <div class="navbar-wagon-item">
              <%= link_to "Sign-up", new_user_registration_path, class: "drop-link" %>
            </div>
          </li>
          <li>
            <div class="navbar-wagon-item">
              <%= link_to "Login", new_user_session_path, class: "drop-link" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/visits/_form.html.erb
<%= simple_form_for([current_user, @visit]) do |f| %>
  <fieldset class="form-group">
    <%= f.label :park %>
    <%= f.association :park, collection: @parks, class: "form-control" %>
  </fieldset>



  <%= f.submit 'Create Visit', class: 'btn btn-primary' %>
<% end %>

app/views/visits/index.html.erb
<div class="park-banner">
  <div class="container park-banner-text">
  <h3>Your Parks</h3>
  </div>
</div>


<div class="container-index">
      <div class="row">
          <% current_user.visits.each do |visit| %>
              <%= link_to park_path(visit.park) do %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card" style="background-image: url(<%= visit.park.image %>)">
                  <div class="card-category"><%=visit.park.name%>
                  </div>
                  <div class="card-description">
                    <h2><%= visit.park.description %></h2>
                    <p><%= visit.park.address %></p>

                  </div>
                  <div>
                    <p class="card-bottom">You Visited <strong><%= visit.park.name %></strong> On <%= visit.date %></p>
                  </div>
              </div>
            <% end %>
          </div>
      <% end %>
    </div>

app/views/visits/new.html.erb
<%= simple_form_for(@visit) do |f| %>
  <%= f.input :date  %>
  <%= f.association :park %>
  <%= f.submit %>
<% end %>